[package]
name = "rs-wasm-strsim"
version = "0.1.0"
authors = ["bossjob-matt <bossjob_matt@proton.me>"]
edition = "2018"
description = "this is a wasm rs demo"
license = "MIT"
repository = "https://github.com/bossjobmatt/wasm-rs-alert"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.95"
wee_alloc = { version = "0.4.5", optional = true }
cfg-if = "1.0.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
strsim = "0.11.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.45"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
